sudo: false
language:
  - node_js
node_js:
  - "8"
dist: trusty
cache:
  directories:
    - node_modules
env:
  - NODE_ENV=test
  jobs:
    include:
      - stage: install
        script:
          - npm install
          - npm run build
      - stage: test
        script:
          - npm run test
      - stage: lint
        script:
          - npm run lint
